### ISSUE TITLE
"statipy" encounter error

### ISSUE THREAD

**Issue by luckypoem** [anjiro/statipy#2]
root@localhost:/usr/local/statipy-site/example# statipy
Traceback (most recent call last):
  File "/usr/local/bin/statipy", line 9, in <module>
    load_entry_point('statipy==0.1', 'console_scripts', 'statipy')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.linux-x86_64/egg/statipy/__init__.py", line 7, in <module>
    # Copyright (c) 1999 by Secret Labs AB.
ImportError: No module named dateutil.parser
root@localhost:/usr/local/statipy-site/example# pip install dateutil.parser
Downloading/unpacking dateutil.parser

  Could not find any downloads that satisfy the requirement dateutil.parser
Cleaning up...
No distributions at all found for dateutil.parser
Storing debug log for failure in /root/.pip/pip.log
root@localhost:/usr/local/statipy-site/example# 

how to fix it?
tks

**Comment by anjiro** [comment]
`pip install python-dateutil`

**Comment by luckypoem** [comment]
root@localhost:/usr/local/statipy-site/example# pip install python-dateutil
root@localhost:/usr/local/statipy-site/example# statipy
Statipy...No site_config.py file found, exiting
root@localhost:/usr/local/statipy-site/example# ls
content  output-old  site_config.py
root@localhost:/usr/local/statipy-site/example# statipy --help
Statipy...No site_config.py file found, exiting
root@localhost:/usr/local/statipy-site/example# statipy .
Statipy...No site_config.py file found, exiting
root@localhost:/usr/local/statipy-site/example#

the site_config.py indeed exists,why the hint says that?
how to fix it?
tks

**Comment by anjiro** [comment]
I've pushed a new version with a debug option. Please install it and run `statipy -d` and paste the output.

**Comment by anjiro** [comment]
Closing this until I get a response with some debugging info.

**Comment by luckypoem** [comment]
hello.

root@localhost:/usr/local/statipy-site/example# statipy -d
Statipy...DEBUG:root:ImportError in loading site_config.py. Current path is: /usr/local/statipy-site/example; files I see:
['output-old', 'content', 'site_config.py']
No site_config.py file found, exiting
root@localhost:/usr/local/statipy-site/example# ls
content  output-old  site_config.py
root@localhost:/usr/local/statipy-site/example# 

tks

**Comment by anjiro** [comment]
It looks like you may have a larger Python issue. In that same directory, run the following and paste the output:

`python -c 'import sys; print sys.path; import site_config'`

**Comment by luckypoem** [comment]
root@localhost:/usr/local/statipy-site/example# python -c 'import sys; print sys.path; import site_config'
['', '/usr/local/lib/python2.7/dist-packages/django_distill-0.6-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/prosopopee-0.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/cssmin-0.2.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/jsmin-2.2.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/CoffeeScript-1.1.2-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/blended-4.8.5-py2.7.egg', '/usr/local/wok-site', '/usr/local/lib/python2.7/dist-packages/Pygments-2.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/Markdown-2.6.5-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/wok-1.0.0b-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/statipy-0.1-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "site_config.py", line 3, in <module>
    import mkdcomments
ImportError: No module named mkdcomments
root@localhost:/usr/local/statipy-site/example#

**Comment by anjiro** [comment]
Ok, there's the problem: the example `site_config.py` requires a number of extra modules. I need to create a readme file explaining this. You'll either want to make your own `site_config.py` from scratch or look at the example `site_config.py` and ensure that you can import all of the modules it loads; if not, install them.

**Comment by anjiro** [comment]
You can also replace `site_config.py` with an empty file and the example will work just fine.

**Comment by luckypoem** [comment]
root@localhost:/usr/local/statipy-site/example# ls
content  output-old  site_config.py.bak  site_config.pyc
root@localhost:/usr/local/statipy-site/example# nano  site_config.py
root@localhost:/usr/local/statipy-site/example# cat site_config.py
root@localhost:/usr/local/statipy-site/example# ls
content  output-old  site_config.py  site_config.py.bak  site_config.pyc
root@localhost:/usr/local/statipy-site/example#
root@localhost:/usr/local/statipy-site/example# statipy
Statipy...No site_config.py file found, exiting
root@localhost:/usr/local/statipy-site/example# 

so using empty site_config.py doesn't work at all.

**Comment by luckypoem** [comment]
root@localhost:/usr/local/statipy-site/example# pip install mkdcomments
Downloading/unpacking mkdcomments
  Could not find any downloads that satisfy the requirement mkdcomments
Cleaning up...
No distributions at all found for mkdcomments
Storing debug log for failure in /root/.pip/pip.log
root@localhost:/usr/local/statipy-site/example#

how to install mkdcomments?

**Comment by anjiro** [comment]
That gets outside of this issue; you'll need to learn about installing Python packages yourself.

**Comment by luckypoem** [comment]
pip install python-markdown-comments to  install mkdcomments sucsussfully.but still encounter 
"No site_config.py file found, exiting" issue,so COULD U PLS write a detailed readme to clarify how to install all the required modules?
thank u very much

**Comment by luckypoem** [comment]
hello.

could u pls upload a requirements.txt file showing all the required modules?
thank u very much

**Comment by anjiro** [comment]
I think if you aren't familiar enough with Python to debug this, Statipy is probably not going to be the right package for you.
